import mongoose, { Schema } from 'mongoose';
const AIModelSchema = new Schema({
    provider: { type: String, enum: ['openai', 'anthropic', 'gemini', 'xai'], required: true },
    modelId: { type: String, required: true, unique: true },
    displayName: { type: String, required: true },
    description: { type: String, default: '' },
    category: { type: String, default: 'General' },
    capabilities: {
        streaming: { type: Boolean, default: true },
        vision: { type: Boolean, default: false },
        functionCalling: { type: Boolean, default: false },
        webSearch: { type: Boolean, default: false },
        reasoning: { type: Boolean, default: false },
    },
    contextWindow: { type: Number, default: 128000 },
    maxOutputTokens: { type: Number, default: 4096 },
    pricing: {
        inputPer1k: { type: Number, default: 0.005 },
        outputPer1k: { type: Number, default: 0.015 },
    },
    enabled: { type: Boolean, default: true },
    isDefault: { type: Boolean, default: false },
}, { timestamps: true });
export const AIModel = mongoose.model('AIModel', AIModelSchema);
// Initial registry seed data
export const DEFAULT_AI_MODELS = [
    {
        provider: 'openai',
        modelId: 'gpt-4o',
        displayName: 'GPT-4o',
        description: 'Flagship versatile multimodal model with rapid high-intelligence responses.',
        category: 'Omni / Multimodal',
        capabilities: { streaming: true, vision: true, functionCalling: true, webSearch: true, reasoning: true },
        contextWindow: 128000,
        maxOutputTokens: 4096,
        pricing: { inputPer1k: 0.0025, outputPer1k: 0.01 },
        enabled: true,
        isDefault: true,
    },
    {
        provider: 'openai',
        modelId: 'gpt-4o-mini',
        displayName: 'GPT-4o Mini',
        description: 'Fast, lightweight intelligence for everyday tasks and low latency.',
        category: 'Fast & Lightweight',
        capabilities: { streaming: true, vision: true, functionCalling: true, webSearch: false, reasoning: false },
        contextWindow: 128000,
        maxOutputTokens: 4096,
        pricing: { inputPer1k: 0.00015, outputPer1k: 0.0006 },
        enabled: true,
    },
    {
        provider: 'anthropic',
        modelId: 'claude-3-7-sonnet-20250219',
        displayName: 'Claude 3.7 Sonnet',
        description: 'Anthropic\'s hybrid model combining instant responses with extended thinking.',
        category: 'Extended Thinking & Code',
        capabilities: { streaming: true, vision: true, functionCalling: true, webSearch: false, reasoning: true },
        contextWindow: 200000,
        maxOutputTokens: 8192,
        pricing: { inputPer1k: 0.003, outputPer1k: 0.015 },
        enabled: true,
    },
    {
        provider: 'anthropic',
        modelId: 'claude-3-5-haiku-20241022',
        displayName: 'Claude 3.5 Haiku',
        description: 'Blazing speed, compact footprint, exceptional coding and chat abilities.',
        category: 'Fast & Lightweight',
        capabilities: { streaming: true, vision: false, functionCalling: true, webSearch: false, reasoning: false },
        contextWindow: 200000,
        maxOutputTokens: 4096,
        pricing: { inputPer1k: 0.0008, outputPer1k: 0.004 },
        enabled: true,
    },
    {
        provider: 'gemini',
        modelId: 'gemini-2.0-flash',
        displayName: 'Gemini 2.0 Flash',
        description: 'Next-gen multimodal model with native tool use, speed, and massive context.',
        category: 'Next-Gen Flash',
        capabilities: { streaming: true, vision: true, functionCalling: true, webSearch: true, reasoning: true },
        contextWindow: 1048576,
        maxOutputTokens: 8192,
        pricing: { inputPer1k: 0.0001, outputPer1k: 0.0004 },
        enabled: true,
    },
    {
        provider: 'gemini',
        modelId: 'gemini-1.5-pro',
        displayName: 'Gemini 1.5 Pro',
        description: 'Google flagship model for deep analysis, massive 2M context documents, and reasoning.',
        category: 'Deep Analysis & Reasoning',
        capabilities: { streaming: true, vision: true, functionCalling: true, webSearch: true, reasoning: true },
        contextWindow: 2097152,
        maxOutputTokens: 8192,
        pricing: { inputPer1k: 0.00125, outputPer1k: 0.005 },
        enabled: true,
    },
    {
        provider: 'xai',
        modelId: 'grok-2-latest',
        displayName: 'Grok 2',
        description: 'xAI advanced intelligence engine with real-time perspective and strong reasoning.',
        category: 'Frontier Intelligence',
        capabilities: { streaming: true, vision: true, functionCalling: true, webSearch: true, reasoning: true },
        contextWindow: 128000,
        maxOutputTokens: 4096,
        pricing: { inputPer1k: 0.002, outputPer1k: 0.01 },
        enabled: true,
    },
];
